import {
  Artist,
  ArtistStatus,
  Booking,
  BookingStatus,
  MoneyAmount,
  PaymentStatus,
  PortfolioImage,
  Review,
  ServicePackage,
} from "@/types/marketplace";

const money = (amount: number): MoneyAmount => ({
  amount,
  currency: "INR",
  display: `₹${amount.toLocaleString("en-IN")}`,
});

export const services: ServicePackage[] = [
  {
    id: "svc-aira-bridal",
    artistId: "artist-1",
    name: "Bridal Signature",
    description: "Soft glam couture finish with premium skin prep.",
    durationMinutes: 150,
    price: money(18000),
    includes: ["Skin prep", "Airbrush base", "Lashes", "Touch-up kit"],
    isActive: true,
  },
  {
    id: "svc-aira-reception",
    artistId: "artist-1",
    name: "Reception Glam",
    description: "High-impact evening glam with sculpted eyes.",
    durationMinutes: 120,
    price: money(14000),
    includes: ["Smokey eye", "HD base", "Lashes"],
    isActive: true,
  },
  {
    id: "svc-meera-party",
    artistId: "artist-2",
    name: "Party Glam",
    description: "Dewy skin and soft definition for celebrations.",
    durationMinutes: 90,
    price: money(9500),
    includes: ["Skin prep", "Dewy base", "Lip color"],
    isActive: true,
  },
  {
    id: "svc-meera-editorial",
    artistId: "artist-2",
    name: "Editorial Look",
    description: "Creative editorial styling for shoots.",
    durationMinutes: 120,
    price: money(12000),
    includes: ["Concept look", "Bold eye", "Gloss finish"],
    isActive: true,
  },
  {
    id: "svc-nyla-bridal",
    artistId: "artist-3",
    name: "Royal Bridal",
    description: "Luxury bridal artistry with gold-toned finish.",
    durationMinutes: 160,
    price: money(20000),
    includes: ["Airbrush base", "Contour", "Lashes"],
    isActive: true,
  },
  {
    id: "svc-nyla-party",
    artistId: "artist-3",
    name: "Evening Glam",
    description: "Elegant party look with luminous highlight.",
    durationMinutes: 100,
    price: money(11000),
    includes: ["Skin prep", "Highlight", "Lip sculpt"],
    isActive: true,
  },
  {
    id: "svc-sana-bridal",
    artistId: "artist-4",
    name: "Classic Bridal",
    description: "Timeless bridal elegance with soft-focus finish.",
    durationMinutes: 140,
    price: money(16000),
    includes: ["Skin prep", "Soft contour", "Lashes"],
    isActive: true,
  },
  {
    id: "svc-sana-corporate",
    artistId: "artist-4",
    name: "Corporate Polish",
    description: "Neutral, camera-ready corporate styling.",
    durationMinutes: 70,
    price: money(7000),
    includes: ["Natural base", "Soft eyes", "Matte lip"],
    isActive: true,
  },
  {
    id: "svc-anaya-editorial",
    artistId: "artist-5",
    name: "Editorial Luxe",
    description: "High fashion editorial makeup for studio shoots.",
    durationMinutes: 130,
    price: money(15000),
    includes: ["Creative eye", "Gloss finish", "Skin prep"],
    isActive: true,
  },
  {
    id: "svc-anaya-party",
    artistId: "artist-5",
    name: "Cocktail Glam",
    description: "Refined glam for cocktail and evening events.",
    durationMinutes: 90,
    price: money(9800),
    includes: ["Dewy base", "Soft highlight", "Lashes"],
    isActive: true,
  },
  {
    id: "svc-leena-bridal",
    artistId: "artist-6",
    name: "South Bridal",
    description: "Traditional bridal with luminous skin tone match.",
    durationMinutes: 150,
    price: money(17500),
    includes: ["Long wear base", "Traditional eyes", "Lashes"],
    isActive: true,
  },
  {
    id: "svc-leena-engagement",
    artistId: "artist-6",
    name: "Engagement Glow",
    description: "Romantic glow for engagement ceremonies.",
    durationMinutes: 110,
    price: money(11500),
    includes: ["Skin prep", "Highlight", "Lip color"],
    isActive: true,
  },
  {
    id: "svc-isha-party",
    artistId: "artist-7",
    name: "Festive Glam",
    description: "Bold festive color with gold accents.",
    durationMinutes: 95,
    price: money(10500),
    includes: ["Gold shimmer", "Matte base", "Lashes"],
    isActive: true,
  },
  {
    id: "svc-isha-shoot",
    artistId: "artist-7",
    name: "Camera Ready",
    description: "High-definition base for shoots and content.",
    durationMinutes: 110,
    price: money(12500),
    includes: ["HD base", "Contour", "Gloss finish"],
    isActive: true,
  },
  {
    id: "svc-ria-bridal",
    artistId: "artist-8",
    name: "Luxury Bridal",
    description: "High-trust bridal glam for premium events.",
    durationMinutes: 155,
    price: money(19000),
    includes: ["Airbrush base", "Sculpted eyes", "Lashes"],
    isActive: true,
  },
  {
    id: "svc-ria-party",
    artistId: "artist-8",
    name: "Party Luxe",
    description: "Modern party glam with gold tones.",
    durationMinutes: 85,
    price: money(9900),
    includes: ["Skin prep", "Shimmer", "Lip sculpt"],
    isActive: true,
  },
];

const beautyPortfolioLibrary = [
  {
    url: "/images/beauty/bridal-1.jpg",
    altText: "Bridal makeup close-up",
    tags: ["bridal", "soft-glam"],
  },
  {
    url: "/images/beauty/bridal-2.jpg",
    altText: "Royal bridal glow",
    tags: ["bridal", "gold"],
  },
  {
    url: "/images/beauty/bridal-3.jpg",
    altText: "Modern bridal elegance",
    tags: ["bridal", "classic"],
  },
  {
    url: "/images/beauty/party-1.jpg",
    altText: "Party glam",
    tags: ["party", "glam"],
  },
  {
    url: "/images/beauty/party-2.jpg",
    altText: "Evening glam",
    tags: ["party", "dewy"],
  },
  {
    url: "/images/beauty/editorial-1.jpg",
    altText: "Editorial statement",
    tags: ["editorial", "studio"],
  },
  {
    url: "/images/beauty/editorial-2.jpg",
    altText: "High fashion editorial",
    tags: ["editorial", "couture"],
  },
  {
    url: "/images/beauty/haldi-1.jpg",
    altText: "Haldi ceremony radiance",
    tags: ["haldi", "warm"],
  },
  {
    url: "/images/beauty/haldi-2.jpg",
    altText: "Traditional haldi glow",
    tags: ["haldi", "traditional"],
  },
  {
    url: "/images/beauty/engagement-1.jpg",
    altText: "Engagement look",
    tags: ["engagement", "romantic"],
  },
  {
    url: "/images/beauty/engagement-2.jpg",
    altText: "Engagement celebration",
    tags: ["engagement", "classic"],
  },
  {
    url: "/images/beauty/glam-1.jpg",
    altText: "Glass skin glam",
    tags: ["glam", "luminous"],
  },
];

const artistIds = [
  "artist-1",
  "artist-2",
  "artist-3",
  "artist-4",
  "artist-5",
  "artist-6",
  "artist-7",
  "artist-8",
];

export const portfolioImages: PortfolioImage[] = Array.from({ length: 24 }).map(
  (_, index) => {
    const libraryItem =
      beautyPortfolioLibrary[index % beautyPortfolioLibrary.length];
    const artistId = artistIds[index % artistIds.length];
    const sortOrder = Math.floor(index / artistIds.length) + 1;
    return {
      id: `pf-${artistId}-${sortOrder}`,
      artistId,
      url: libraryItem.url,
      altText: libraryItem.altText,
      tags: libraryItem.tags,
      isFeatured: sortOrder === 1,
      sortOrder,
      createdAt: "2026-02-01T10:00:00Z",
    };
  },
);

export const artists: Artist[] = [
  {
    id: "artist-1",
    name: "Aira Khan",
    profileImage: "/images/beauty/bridal-1.jpg",
    rating: 4.9,
    reviewCount: 120,
    priceFrom: money(14000),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 8,
    completionRate: 98,
    responseTime: "Within 1 hour",
    location: {
      label: "Indiranagar, Bengaluru",
      city: "Bengaluru",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-1"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-1"),
    about: "Luxury bridal specialist with couture soft glam artistry.",
  },
  {
    id: "artist-2",
    name: "Meera Rao",
    profileImage: "/images/beauty/party-1.jpg",
    rating: 4.8,
    reviewCount: 98,
    priceFrom: money(9500),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 6,
    completionRate: 96,
    responseTime: "Within 2 hours",
    location: {
      label: "Bandra, Mumbai",
      city: "Mumbai",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-2"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-2"),
    about: "Party and editorial glam with luminous skin finish.",
  },
  {
    id: "artist-3",
    name: "Nyla Kapoor",
    profileImage: "/images/beauty/bridal-2.jpg",
    rating: 4.7,
    reviewCount: 74,
    priceFrom: money(11000),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 7,
    completionRate: 95,
    responseTime: "Within 1 hour",
    location: {
      label: "Defence Colony, Delhi",
      city: "Delhi",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-3"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-3"),
    about: "Royal bridal specialist with gold-toned finish.",
  },
  {
    id: "artist-4",
    name: "Sana Iyer",
    profileImage: "/images/beauty/editorial-1.jpg",
    rating: 4.6,
    reviewCount: 62,
    priceFrom: money(7000),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 5,
    completionRate: 94,
    responseTime: "Within 3 hours",
    location: {
      label: "Koregaon Park, Pune",
      city: "Pune",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-4"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-4"),
    about: "Classic bridal and corporate polish with subtle elegance.",
  },
  {
    id: "artist-5",
    name: "Anaya Bose",
    profileImage: "/images/beauty/editorial-2.jpg",
    rating: 4.9,
    reviewCount: 140,
    priceFrom: money(9800),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 9,
    completionRate: 97,
    responseTime: "Within 1 hour",
    location: {
      label: "Salt Lake, Kolkata",
      city: "Kolkata",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-5"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-5"),
    about: "Editorial artist for fashion and couture shoots.",
  },
  {
    id: "artist-6",
    name: "Leena Sharma",
    profileImage: "/images/beauty/haldi-1.jpg",
    rating: 4.7,
    reviewCount: 88,
    priceFrom: money(11500),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 7,
    completionRate: 96,
    responseTime: "Within 2 hours",
    location: {
      label: "Banjara Hills, Hyderabad",
      city: "Hyderabad",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-6"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-6"),
    about: "South bridal artistry with luminous long-wear finish.",
  },
  {
    id: "artist-7",
    name: "Isha Menon",
    profileImage: "/images/beauty/glam-1.jpg",
    rating: 4.6,
    reviewCount: 60,
    priceFrom: money(10500),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 4,
    completionRate: 93,
    responseTime: "Within 4 hours",
    location: {
      label: "Panaji, Goa",
      city: "Goa",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-7"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-7"),
    about: "Festive glam specialist with gold shimmer accents.",
  },
  {
    id: "artist-8",
    name: "Ria Kapoor",
    profileImage: "/images/beauty/engagement-1.jpg",
    rating: 4.8,
    reviewCount: 102,
    priceFrom: money(12000),
    verified: true,
    artistStatus: ArtistStatus.Approved,
    experienceYears: 6,
    completionRate: 95,
    responseTime: "Within 1 hour",
    location: {
      label: "Powai, Mumbai",
      city: "Mumbai",
      country: "India",
    },
    services: services.filter((service) => service.artistId === "artist-8"),
    portfolio: portfolioImages.filter((image) => image.artistId === "artist-8"),
    about: "Luxury bridal glam for premium events and couture looks.",
  },
];

export const bookings: Booking[] = [
  {
    id: "SNGR-3001",
    customerId: "cust-1",
    artistId: "artist-1",
    serviceId: "svc-aira-bridal",
    date: "2026-07-12",
    time: "10:00",
    location: {
      label: "Indiranagar, Bengaluru",
      city: "Bengaluru",
      country: "India",
    },
    totalPrice: money(18000),
    platformFee: money(900),
    status: BookingStatus.Confirmed,
    createdAt: "2026-06-28T09:00:00Z",
    skinTone: "Warm",
    skinType: "Normal",
    stylePreference: "Soft glam, dewy finish",
    consentForImages: true,
    payment: {
      subtotal: money(18000),
      platformFee: money(900),
      total: money(18900),
      paymentStatus: PaymentStatus.Paid,
      paymentMethod: "UPI",
      transactionId: "TXN-8891",
    },
  },
  {
    id: "SNGR-3002",
    customerId: "cust-2",
    artistId: "artist-2",
    serviceId: "svc-meera-party",
    date: "2026-07-14",
    time: "18:30",
    location: {
      label: "Bandra, Mumbai",
      city: "Mumbai",
      country: "India",
    },
    totalPrice: money(9500),
    platformFee: money(475),
    status: BookingStatus.Confirmed,
    createdAt: "2026-06-29T11:20:00Z",
    skinTone: "Neutral",
    skinType: "Combination",
    stylePreference: "Natural glow",
    consentForImages: false,
    payment: {
      subtotal: money(9500),
      platformFee: money(475),
      total: money(9975),
      paymentStatus: PaymentStatus.Paid,
      paymentMethod: "Card",
      transactionId: "TXN-8892",
    },
  },
  {
    id: "SNGR-3003",
    customerId: "cust-3",
    artistId: "artist-3",
    serviceId: "svc-nyla-bridal",
    date: "2026-08-01",
    time: "09:00",
    location: {
      label: "Defence Colony, Delhi",
      city: "Delhi",
      country: "India",
    },
    totalPrice: money(20000),
    platformFee: money(1000),
    status: BookingStatus.Pending,
    createdAt: "2026-06-30T08:10:00Z",
    skinTone: "Warm",
    skinType: "Dry",
    stylePreference: "Gold-toned bridal glam",
    consentForImages: true,
    payment: {
      subtotal: money(20000),
      platformFee: money(1000),
      total: money(21000),
      paymentStatus: PaymentStatus.Authorized,
      paymentMethod: "UPI",
      transactionId: "TXN-8893",
    },
  },
  {
    id: "SNGR-3004",
    customerId: "cust-4",
    artistId: "artist-4",
    serviceId: "svc-sana-corporate",
    date: "2026-07-03",
    time: "07:30",
    location: {
      label: "Koregaon Park, Pune",
      city: "Pune",
      country: "India",
    },
    totalPrice: money(7000),
    platformFee: money(350),
    status: BookingStatus.Completed,
    createdAt: "2026-06-12T06:40:00Z",
    payment: {
      subtotal: money(7000),
      platformFee: money(350),
      total: money(7350),
      paymentStatus: PaymentStatus.Paid,
      paymentMethod: "Card",
      transactionId: "TXN-8894",
    },
  },
  {
    id: "SNGR-3005",
    customerId: "cust-5",
    artistId: "artist-5",
    serviceId: "svc-anaya-editorial",
    date: "2026-07-18",
    time: "13:00",
    location: {
      label: "Salt Lake, Kolkata",
      city: "Kolkata",
      country: "India",
    },
    totalPrice: money(15000),
    platformFee: money(750),
    status: BookingStatus.Confirmed,
    createdAt: "2026-06-24T12:15:00Z",
    skinTone: "Cool",
    skinType: "Normal",
    stylePreference: "High fashion editorial",
    consentForImages: true,
    payment: {
      subtotal: money(15000),
      platformFee: money(750),
      total: money(15750),
      paymentStatus: PaymentStatus.Paid,
      paymentMethod: "UPI",
      transactionId: "TXN-8895",
    },
  },
  {
    id: "SNGR-3006",
    customerId: "cust-6",
    artistId: "artist-6",
    serviceId: "svc-leena-engagement",
    date: "2026-07-21",
    time: "16:00",
    location: {
      label: "Banjara Hills, Hyderabad",
      city: "Hyderabad",
      country: "India",
    },
    totalPrice: money(11500),
    platformFee: money(575),
    status: BookingStatus.Confirmed,
    createdAt: "2026-06-26T10:30:00Z",
    skinTone: "Warm",
    skinType: "Oily",
    stylePreference: "Romantic glow",
    consentForImages: true,
    payment: {
      subtotal: money(11500),
      platformFee: money(575),
      total: money(12075),
      paymentStatus: PaymentStatus.Paid,
      paymentMethod: "Card",
      transactionId: "TXN-8896",
    },
  },
  {
    id: "SNGR-3007",
    customerId: "cust-7",
    artistId: "artist-7",
    serviceId: "svc-isha-party",
    date: "2026-07-09",
    time: "19:00",
    location: {
      label: "Panaji, Goa",
      city: "Goa",
      country: "India",
    },
    totalPrice: money(10500),
    platformFee: money(525),
    status: BookingStatus.Cancelled,
    createdAt: "2026-06-20T13:45:00Z",
    skinTone: "Neutral",
    skinType: "Combination",
    stylePreference: "Festive glam with gold shimmer",
    consentForImages: false,
    payment: {
      subtotal: money(10500),
      platformFee: money(525),
      total: money(11025),
      paymentStatus: PaymentStatus.Refunded,
      paymentMethod: "UPI",
      transactionId: "TXN-8897",
    },
  },
  {
    id: "SNGR-3008",
    customerId: "cust-8",
    artistId: "artist-8",
    serviceId: "svc-ria-bridal",
    date: "2026-08-06",
    time: "08:30",
    location: {
      label: "Powai, Mumbai",
      city: "Mumbai",
      country: "India",
    },
    totalPrice: money(19000),
    platformFee: money(950),
    status: BookingStatus.Pending,
    createdAt: "2026-06-30T14:05:00Z",
    skinTone: "Warm",
    skinType: "Normal",
    stylePreference: "Luxury bridal glam",
    consentForImages: true,
    payment: {
      subtotal: money(19000),
      platformFee: money(950),
      total: money(19950),
      paymentStatus: PaymentStatus.Authorized,
      paymentMethod: "Card",
      transactionId: "TXN-8898",
    },
  },
  {
    id: "SNGR-3009",
    customerId: "cust-9",
    artistId: "artist-2",
    serviceId: "svc-meera-editorial",
    date: "2026-07-25",
    time: "12:00",
    location: {
      label: "Lower Parel, Mumbai",
      city: "Mumbai",
      country: "India",
    },
    totalPrice: money(12000),
    platformFee: money(600),
    status: BookingStatus.Completed,
    createdAt: "2026-06-18T07:45:00Z",
    skinTone: "Cool",
    skinType: "Normal",
    stylePreference: "Editorial glossy",
    consentForImages: true,
    payment: {
      subtotal: money(12000),
      platformFee: money(600),
      total: money(12600),
      paymentStatus: PaymentStatus.Paid,
      paymentMethod: "Card",
      transactionId: "TXN-8899",
    },
  },
  {
    id: "SNGR-3010",
    customerId: "cust-10",
    artistId: "artist-4",
    serviceId: "svc-sana-bridal",
    date: "2026-07-28",
    time: "10:30",
    location: {
      label: "Koregaon Park, Pune",
      city: "Pune",
      country: "India",
    },
    totalPrice: money(16000),
    platformFee: money(800),
    status: BookingStatus.Confirmed,
    createdAt: "2026-06-27T09:25:00Z",
    skinTone: "Neutral",
    skinType: "Dry",
    stylePreference: "Classic bridal elegance",
    consentForImages: true,
    payment: {
      subtotal: money(16000),
      platformFee: money(800),
      total: money(16800),
      paymentStatus: PaymentStatus.Paid,
      paymentMethod: "UPI",
      transactionId: "TXN-8900",
    },
  },
];

export const reviews: Review[] = [
  {
    id: "rev-1",
    artistId: "artist-1",
    bookingId: "SNGR-3001",
    authorId: "cust-1",
    authorName: "Rhea Kapoor",
    rating: 5,
    comment: "Impeccable bridal finish and calming presence.",
    createdAt: "2026-07-13T10:00:00Z",
  },
  {
    id: "rev-2",
    artistId: "artist-1",
    bookingId: "SNGR-3001",
    authorId: "cust-1",
    authorName: "Rhea Kapoor",
    rating: 5,
    comment: "Loved the soft glam and attention to detail.",
    createdAt: "2026-07-13T12:00:00Z",
  },
  {
    id: "rev-3",
    artistId: "artist-2",
    bookingId: "SNGR-3002",
    authorId: "cust-2",
    authorName: "Neha Verma",
    rating: 5,
    comment: "Party glam was flawless and long-lasting.",
    createdAt: "2026-07-15T09:00:00Z",
  },
  {
    id: "rev-4",
    artistId: "artist-2",
    bookingId: "SNGR-3009",
    authorId: "cust-9",
    authorName: "Ira B",
    rating: 4,
    comment: "Editorial look was on point for the shoot.",
    createdAt: "2026-07-26T10:00:00Z",
  },
  {
    id: "rev-5",
    artistId: "artist-3",
    bookingId: "SNGR-3003",
    authorId: "cust-3",
    authorName: "Tara Singh",
    rating: 5,
    comment: "Royal bridal glam exceeded expectations.",
    createdAt: "2026-08-02T09:30:00Z",
  },
  {
    id: "rev-6",
    artistId: "artist-4",
    bookingId: "SNGR-3004",
    authorId: "cust-4",
    authorName: "Asha Rao",
    rating: 4,
    comment: "Elegant and professional corporate polish.",
    createdAt: "2026-07-04T09:00:00Z",
  },
  {
    id: "rev-7",
    artistId: "artist-4",
    bookingId: "SNGR-3010",
    authorId: "cust-10",
    authorName: "Maya K",
    rating: 5,
    comment: "Classic bridal look with beautiful finish.",
    createdAt: "2026-07-29T10:00:00Z",
  },
  {
    id: "rev-8",
    artistId: "artist-5",
    bookingId: "SNGR-3005",
    authorId: "cust-5",
    authorName: "Zara Ali",
    rating: 5,
    comment: "Editorial luxe was stunning for the campaign.",
    createdAt: "2026-07-19T11:00:00Z",
  },
  {
    id: "rev-9",
    artistId: "artist-6",
    bookingId: "SNGR-3006",
    authorId: "cust-6",
    authorName: "Divya R",
    rating: 4,
    comment: "Engagement glow was soft and radiant.",
    createdAt: "2026-07-22T09:20:00Z",
  },
  {
    id: "rev-10",
    artistId: "artist-7",
    bookingId: "SNGR-3007",
    authorId: "cust-7",
    authorName: "Lina D",
    rating: 4,
    comment: "Festive glam was vibrant and camera-ready.",
    createdAt: "2026-07-10T08:15:00Z",
  },
  {
    id: "rev-11",
    artistId: "artist-8",
    bookingId: "SNGR-3008",
    authorId: "cust-8",
    authorName: "Ritika Jain",
    rating: 5,
    comment: "Luxury bridal glam with perfect tone match.",
    createdAt: "2026-08-07T10:45:00Z",
  },
  {
    id: "rev-12",
    artistId: "artist-8",
    bookingId: "SNGR-3008",
    authorId: "cust-8",
    authorName: "Ritika Jain",
    rating: 5,
    comment: "Professional, punctual, and flawless finish.",
    createdAt: "2026-08-07T12:00:00Z",
  },
];
